### ISSUE TITLE
Login fails with a Error 500

### ISSUE THREAD

**Issue by adittmar** [DMKEBUSINESSGMBH/mksamlauth#25]
Hello

We are currently evaluating the extension for a running project. When using the fe-login form, a Error 500 is thrown instantly after sending the form. Currently we have no additional information available (such in Logfiles), it just happens as soon as mksamlauth is activated.

We've setup everything accordingly the Admin-manual provided in the Documentation-folder.
Currently the IT-Department states that the SAML-Service is running on their side. The Identity Provider record is added and filled with the required data.

So for the moment we're seeking for answers to several questions in order to better understand the problem and probably being able in order to narrow down the possible reasons for this problem.

1. Is the admin-documentation in the extension folder stil up to date or is perhaps something missing there?

2. We also tried to setup a Service provider record, but TYPO3 is not able to save it. Reason seems to that this table is provided via TCA but is missing as field definitions in the ext_table.sql? So can we ignore this record at all? Is it just a remaining part of an ongoing development?

3. Any other hints for giving a direction are highly appreciated.

Thanks so far and looking forward to get some more insights ;-)

Best regards
Andre

**Comment by Baachi** [comment]
Hey @adittmar,

sorry for the long delay! 
Did you installed the extension via composer or typo3 extension manager? 

Did you checked the logs from the webserver/php as well? Normally if something goes wrong, it should be logged somewhere. 

> Is the admin-documentation in the extension folder stil up to date or is perhaps something missing there?

The documentation is still up to date, but not fully completed. We want to add some HowTo guides how to setup this extension.

> We also tried to setup a Service provider record, but TYPO3 is not able to save it. Reason seems to that this table is provided via TCA but is missing as field definitions in the ext_table.sql? So can we ignore this record at all? Is it just a remaining part of an ongoing development?

Yes this indeed a error in this example. In the early days there exists two tables. This error has been fixed in the next version. We hope to publish this in the next upcoming days.

Sorry, that i can't fix your problem. :cry:

**Comment by RocKordier** [comment]
Closed due to inactivity. Please reopen or create a new issue for further problems.
